package com.aditya.worker;
import com.fasterxml.jackson.databind.*; import org.springframework.data.redis.core.StringRedisTemplate; import org.springframework.scheduling.annotation.Scheduled; import org.springframework.stereotype.Component; import java.util.*;
@Component public class Worker {
 private final StringRedisTemplate redis; private final ObjectMapper mapper; private final Random random=new Random(); private final int maxRetries=3;
 public Worker(StringRedisTemplate r,ObjectMapper m){redis=r;mapper=m;}
 @Scheduled(fixedDelay=500) public void poll(){String id=redis.opsForList().leftPop("jobs:queue"); if(id==null)return; try{process(id);}catch(Exception e){handleFailure(id);}}
 void process(String id)throws Exception{String raw=redis.opsForValue().get("job:"+id); if(raw==null)return; Map<String,Object> j=mapper.readValue(raw,Map.class); int attempts=((Number)j.getOrDefault("attempts",0)).intValue()+1; j.put("attempts",attempts); j.put("status","PROCESSING"); j.put("updatedAt",System.currentTimeMillis()); redis.opsForValue().set("job:"+id,mapper.writeValueAsString(j)); String type=String.valueOf(j.get("type")); if("FAIL".equalsIgnoreCase(type)||String.valueOf(j.get("payload")).toLowerCase().contains("fail")){throw new IllegalStateException("Simulated failure");} Thread.sleep(300); j.put("status","COMPLETED");j.put("updatedAt",System.currentTimeMillis());redis.opsForValue().set("job:"+id,mapper.writeValueAsString(j)); redis.opsForList().rightPush("jobs:completed",id); }
 void handleFailure(String id){try{String raw=redis.opsForValue().get("job:"+id);if(raw==null)return;Map<String,Object> j=mapper.readValue(raw,Map.class);int attempts=((Number)j.getOrDefault("attempts",0)).intValue();j.put("status","FAILED");j.put("updatedAt",System.currentTimeMillis());redis.opsForValue().set("job:"+id,mapper.writeValueAsString(j));if(attempts<maxRetries){redis.opsForList().rightPush("jobs:queue",id);}else{redis.opsForList().rightPush("jobs:dead",id);}}catch(Exception ignored){}}
}
